# Assignment – Model Selection

In [74]:
import pandas as pd
import numpy as np

1. Load the dataset into python environment

In [2]:
data=pd.read_csv(r"C:\Users\Workstation X\Desktop\ICT\Assignment on model selection\titanic_dataset .csv")

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# 2. Pre-processing steps

In [5]:
data.shape

(891, 12)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [7]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [8]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
## Summary - There are null values in columns 'Age', 'Cabin', and 'Embarked' in this dataset.

In [9]:
## To display columns with missing values - just checking with another method
columns_with_missing_values = data.columns[data.isna().any()].tolist()

print("Columns with missing values:")
for column in columns_with_missing_values:
    print(column)

Columns with missing values:
Age
Cabin
Embarked


In [10]:
data['Embarked'].nunique()

3

In [11]:
data['PassengerId'].nunique()

891

In [12]:
data['Name'].nunique()

891

In [13]:
data['Ticket'].nunique()

681

In [14]:
data['Cabin'].nunique()

147

In [15]:
# Dropping 3 columns which are not useful in this case.

columns_to_drop=['PassengerId','Name','Ticket','Cabin']
data=data.drop(columns_to_drop,axis=1)
data

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [16]:
data.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [17]:
## Filling the missing values in AGE column.

## Fill missing "Age" values with the mean
data['Age'].fillna(data['Age'].mean(), inplace=True)

data.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [18]:
## Doing the normalisation or scaling method.

from sklearn.preprocessing import MinMaxScaler

# Separate the target ("Survived") from the features
target = data['Embarked']
features = data.drop(columns=['Embarked'])

# Identify numerical columns (exclude categorical columns)
numerical_columns = features.select_dtypes(include=['number']).columns

scaler = MinMaxScaler()

# Apply MinMax scaling to the numerical features
features[numerical_columns] = scaler.fit_transform(features[numerical_columns])

# Combine the scaled features and the target back into a DataFrame
data_scaled = pd.concat([features, target], axis=1)

data_scaled.head()

Survived  Pclass     Sex       Age  SibSp  Parch      Fare Embarked
0       0.0     1.0    male  0.271174  0.125    0.0  0.014151        S
1       1.0     0.0  female  0.472229  0.125    0.0  0.139136        C
2       1.0     1.0  female  0.321438  0.000    0.0  0.015469        S
3       1.0     0.0  female  0.434531  0.125    0.0  0.103644        S
4       0.0     1.0    male  0.434531  0.000    0.0  0.015713        S

In [20]:
## Label Encoding


# Define a mapping for label encoding
sex_mapping = {'male': 0, 'female': 1}

# Apply label encoding to the "Sex" column
data_scaled['Sex'] = data_scaled['Sex'].map(sex_mapping)

# Display the DataFrame after label encoding
print("\nDataFrame after Label Encoding on 'Sex' column:")
data_scaled.head()



DataFrame after Label Encoding on 'Sex' column:


Survived  Pclass  Sex       Age  SibSp  Parch      Fare Embarked
0       0.0     1.0    0  0.271174  0.125    0.0  0.014151        S
1       1.0     0.0    1  0.472229  0.125    0.0  0.139136        C
2       1.0     1.0    1  0.321438  0.000    0.0  0.015469        S
3       1.0     0.0    1  0.434531  0.125    0.0  0.103644        S
4       0.0     1.0    0  0.434531  0.000    0.0  0.015713        S

In [21]:
data_scaled.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64

In [22]:
## Deleting rows of null values in Embarked column

data_scaled=data_scaled.dropna(subset=['Embarked'])
data_scaled.head()

Survived  Pclass  Sex       Age  SibSp  Parch      Fare Embarked
0       0.0     1.0    0  0.271174  0.125    0.0  0.014151        S
1       1.0     0.0    1  0.472229  0.125    0.0  0.139136        C
2       1.0     1.0    1  0.321438  0.000    0.0  0.015469        S
3       1.0     0.0    1  0.434531  0.125    0.0  0.103644        S
4       0.0     1.0    0  0.434531  0.000    0.0  0.015713        S

In [23]:
data_scaled.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [ ]:
# There are no more null or missing values now.

In [24]:
data_scaled['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [25]:
## Label Encoding on Embarked Column

# Define a mapping for label encoding
embarked_mapping = {'S': 1, 'C': 2, 'Q': 3}

# Apply label encoding to the "Sex" column
data_scaled['Embarked'] = data_scaled['Embarked'].map(embarked_mapping)

data_scaled.head()

Survived  Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0       0.0     1.0    0  0.271174  0.125    0.0  0.014151         1
1       1.0     0.0    1  0.472229  0.125    0.0  0.139136         2
2       1.0     1.0    1  0.321438  0.000    0.0  0.015469         1
3       1.0     0.0    1  0.434531  0.125    0.0  0.103644         1
4       0.0     1.0    0  0.434531  0.000    0.0  0.015713         1

# 3. Create kNN and SVM models

In [ ]:
## K-Nearest neighbors Classification

In [43]:
## Dividing data into features and labels

X = data_scaled.iloc[:,0:-1]
y = data_scaled['Embarked'].values

In [44]:
## Spliting dataset into training set and test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [54]:
## Fit the model

# Fitting clasifier to the Training set
from sklearn.neighbors import KNeighborsClassifier

# Instantiate learning model (k = 3)
knn_classifier = KNeighborsClassifier(n_neighbors=3)

# Fitting the model
knn_classifier=classifier.fit(X_train, y_train)

In [55]:
score=knn_classifier.score(X_test,y_test)
print("Accuracy of our model is equal to " + str(round(score*100,2))+"%")

Accuracy of our model is equal to 72.47%


In [ ]:
## Support Vector Machines

In [49]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [50]:
from sklearn.svm import SVC

# Create and train a Support Vector Classifier (SVC)
svc_classifier = SVC()


svc_classifier=svc_classifier.fit(X_train, Y_train)


In [51]:
svc_score=svc_classifier.score(X_test,y_test)
print("Accuracy of our model is equal to " + str(round(svc_score*100,2))+"%")

Accuracy of our model is equal to 73.6%


# 4. Do k-fold and stratified k-fold cross validation techniques and find the average accuracy score of the models.

In [ ]:
# K-fold validation

In [53]:
from sklearn.model_selection import KFold
kfold_validator= KFold(10)
for train_index, test_index in kfold_validator.split(X,y):
    print("Training Index: ", train_index)
    print("Testing Index: ", test_index)

Training Index:  [ 89  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106
 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124
 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142
 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160
 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178
 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196
 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214
 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232
 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250
 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268
 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286
 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304
 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322
 323 324 325 326 327 328 329 330 3

In [ ]:
# Checking result from KNN method

In [58]:
from sklearn.model_selection import cross_val_score
cv_result_knn=cross_val_score(knn_classifier,X,y,cv=kfold_validator)

In [59]:
cv_result_knn

array([0.66292135, 0.76404494, 0.73033708, 0.69662921, 0.74157303,
       0.76404494, 0.76404494, 0.73033708, 0.71910112, 0.70454545])

In [75]:
np.mean(cv_result_knn)

0.7277579162410623

In [ ]:
# Checking result from SVM method

In [60]:
cv_result_svc=cross_val_score(knn_classifier,X,y,cv=kfold_validator)

In [61]:
cv_result_svc

array([0.66292135, 0.76404494, 0.73033708, 0.69662921, 0.74157303,
       0.76404494, 0.76404494, 0.73033708, 0.71910112, 0.70454545])

In [62]:
np.mean(cv_result_svc)

0.7277579162410623

In [ ]:
# Stratified cross validation

In [67]:
from sklearn.model_selection import StratifiedKFold
skfold_validator=StratifiedKFold(n_splits=10)

In [68]:
for train_index, test_index in skfold_validator.split(X,y):
    print("Training Index: ", train_index)
    print("Testing Index: ", test_index)

Training Index:  [ 47  64  72  81  93  94  95  96  97  98  99 100 101 102 103 104 105 106
 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124
 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142
 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160
 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178
 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196
 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214
 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232
 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250
 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268
 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286
 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304
 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322
 323 324 325 326 327 328 329 330 3

In [ ]:
# Checking result from KNN method

In [69]:
scv_result_knn=cross_val_score(knn_classifier,X,y,cv=skfold_validator)

In [70]:
scv_result_knn

array([0.6741573 , 0.74157303, 0.73033708, 0.73033708, 0.75280899,
       0.7752809 , 0.74157303, 0.73033708, 0.66292135, 0.72727273])

In [76]:
np.mean(scv_result_knn)

0.7266598569969356

In [ ]:
# Checking result from SVM method

In [71]:
scv_result_svc=cross_val_score(svc_classifier,X,y,cv=skfold_validator)

In [72]:
scv_result_svc

array([0.73033708, 0.73033708, 0.73033708, 0.73033708, 0.71910112,
       0.71910112, 0.71910112, 0.73033708, 0.73033708, 0.72727273])

In [73]:
np.mean(scv_result_svc)

0.7266598569969357